### ISSUE TITLE
Clone repo

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/ide-ext-vscode#11]
Goal: Provide a mechanism to clone the repo specified in challenge payload (this will be on v5 challenge API). This could be an automatic option or on demand from the challenge details page. This will set up the code for workspace for the user

**Comment by callmekatootie** [comment]
v5 challenge api has the `gitRepoURLs` field that will contain the git repo url.

But this is right now an array and not a single repo (understandably). Will take the easier route and assume we will be dealing with only 1 repo at a time

**Comment by callmekatootie** [comment]
Faced an issue during challenge creation with repo url:

```
{
    "message": "\"gitRepoURLs\" is not allowed"
}
```

Checking with Thomas about it...

**Comment by cwdcwd** [comment]
👍 
for the repos array, let's assume one at first but would be cool maybe to offer the option which to clone and add to the workspace

**Comment by callmekatootie** [comment]
@cwdcwd This won't be part of the current milestone, since we are focusing only on v4 challenge api related features for now.

**Comment by callmekatootie** [comment]
Or - we could perhaps prompt the user to clone any existing starter packs for the project (based on the tags assigned to the project perhaps?)

**Comment by cwdcwd** [comment]
I like that idea

**Comment by callmekatootie** [comment]
The user is now presented with option to clone a starter pack when they register for a contest
