### ISSUE TITLE
auto fill .topcoderrc

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/ide-ext-vscode#12]
Goal: Set the challenge Id into the `.topcoderrc`  file automatically for the user when they register and check out/clone a project. The idea is to keep the user out of the `.topcoderrc`  file

**Comment by callmekatootie** [comment]
@cwdcwd This won't be part of the current milestone, since we are focusing only on v4 challenge api related features for now.

Or - we could perhaps prompt the user to clone any existing starter packs for the project (based on the tags assigned to the project perhaps?)

**Comment by cwdcwd** [comment]
let's go on registration

**Comment by callmekatootie** [comment]
Contest launched: http://www.topcoder.com/challenge-details/30099778/?type=develop

**Comment by callmekatootie** [comment]
This has now been carried out.
