### ISSUE TITLE
submission details

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/ide-ext-vscode#14]
Goal: To show details and status of a submission some where (maybe in the screen of #10) details of the user's submission (reviews, artifacts, etc) for the challenge specified

**Comment by callmekatootie** [comment]
@cwdcwd In order to show submission details, the user should first upload their submission.

However, at the moment, since we are switching over to v5 challenge api, submission api does not support it yet - so we cannot upload the solution to a challenge that exists in v5.

Could you let me know how you would like me to proceed here

**Comment by cwdcwd** [comment]
target v4 for now

**Comment by callmekatootie** [comment]
I have updated #10 with the details - essentially, we will be displaying the list of contests that the user has submitted for - so **Question 1 - Which API can tell me the contests for which the user has an active submission?**

**Question 2 - Which API can give me details about the review scores for the member's submission and any other info that one usually sees in OR perhaps?**

**Comment by cwdcwd** [comment]
1. I think "active" implies that the challenge is still open and submittable, right? That could be determined from the phase of the challenge `/challenges/{id}/phases`. In the context of the IDE I think we should just start with the challenges that are in the rc file. 
2. `/v5/submissions?challengId={challengeId}& memberId={memberId}` should give you all the submissions for a member on a specific challenge and the submission records will have their reviews inside them.

**Comment by callmekatootie** [comment]
1. No. This ticket says "submission" details. So I would expect an API that tells me the contests where:

- I have registered AND
- I have submitted AND
- Submission phase has closed and we are in the Review+ phases

2. Correct me if I am wrong here but I recollect that we don't yet display the scores from OR through the submission API - and we only have the scores from Antivirus, automated scorers etc - should I work with these for now or should I expect the scores from OR to be displayed (in which case where do I get those from)

**Comment by cwdcwd** [comment]
by submission details I'm thinking the review records on the submission record. 
for OR reviews, I'm going to get that turned on ...

**Comment by callmekatootie** [comment]
Ah ok. Alright - I'll work with the submission API here and set this up for easy development.

**Comment by callmekatootie** [comment]
The user can see their reviews and artifacts, if any in the Topcoder Activity Bar
