### ISSUE TITLE
Telemetry Feature

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/ide-ext-vscode#20]
Capture user interaction with our extension to improve the extension and create our own user metrics.

Explore this [reference](https://aws.amazon.com/pinpoint/features/analytics/usage-analytics/).

We need to setup our own endpoint to capture these metrics (either anonymously or through jwt tokens) and also update our Privacy Policy to mention this

**Comment by callmekatootie** [comment]
Can't we use Google Analytics here?

**Comment by callmekatootie** [comment]
Need to support anonymous collection of data too

**Comment by callmekatootie** [comment]
Provided feature for telemetry. But it isn't anonymous yet so keeping ticket

**Comment by callmekatootie** [comment]
Came across this module today: https://www.npmjs.com/package/vscode-extension-telemetry

**Comment by cwdcwd** [comment]
closing as I think we've got this in, at least rudimentarily, now
