### ISSUE TITLE
Display time until end of submission phase

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/ide-ext-vscode#21]
A timer like [this](https://marketplace.visualstudio.com/items?itemName=mlazzarini.pair-programming-timer) that displays the hours until the end of the submission phase

**Comment by callmekatootie** [comment]
- It needs the `.topcoderrc` file to be present in the current workspace at the ROOT folder.
- We could fetch the details of the contest using the id in the `.topcoderrc` file and then determine the time until the end of submission phase (if it is still active).

It can silently do its job - if there is no `.topcoderrc` file, or the file is not configured correctly in which case its not possible to get the challenge details or the api call fails - in any of these conditions, it can simply ignore the error and not show itself (and not show any error message to the user too).

A silent feature.

**Comment by cwdcwd** [comment]
should we expand to a `/.topcoder` folder for the details and pull down the whole challenge JSON?

**Comment by callmekatootie** [comment]
Yes - that's a good idea

**Comment by callmekatootie** [comment]
`.topcoder` folder take up in https://github.com/topcoder-platform/ide-ext-vscode/issues/37

Closing this ticket since original feature has been implemented
