### ISSUE TITLE
Time in EDT

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/ide-ext-vscode#22]
Since OR displays the time in EDT, it would be nice to have the editor display the current time in EDT in the Side Bar / Status Bar

**Comment by cwdcwd** [comment]
V5 submission API should be in UTC time w/ offsets. 
V5 challenge API will be the same. 
if pulling details from v3/v4 API then assume EDT, otherwise UTC

**Comment by callmekatootie** [comment]
This has now been implemented
