### ISSUE TITLE
Topcoder does not indicate I have registered, even though the action through the extension worked

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/ide-ext-vscode#26]
I registered for this contest through the extension: http://www.topcoder.com/challenges/30100192?tab=registrants

I even got an email from Topcoder confirming my registration.

However, that challenge still shows me the REGISTER button and I don't appear in the list of registrants for that contest

**Comment by cwdcwd** [comment]
that could just be a failure of the v3/v4 challenge API elastic search feeder.
v5 shouldn't have this issue
