### ISSUE TITLE
add extension recommendations

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/ide-ext-vscode#52]
[see this](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions)
recommended extensions would be:
- [VS Live Share Extensions Pack](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare-pack)
- [Live Share Spaces](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.spaces)
- [Remote Development Pack](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack)

**Comment by callmekatootie** [comment]
Update: Changes are in. Will be part of next release

**Comment by callmekatootie** [comment]
Released in https://github.com/topcoder-platform/ide-ext-vscode/releases/tag/v0.2.0
