### ISSUE TITLE
Home menu links not working

### ISSUE THREAD

**Issue by veshu** [topcoder-platform/ide-ext-vscode#56]
Following menu links are not working 
`Extension Features`
`Getting Started`

![image](https://user-images.githubusercontent.com/2202045/68267454-9b50df00-007a-11ea-90d7-07d0c508a6fb.png)

OS: macOS catalina 10.15
VSC: Version: 1.39.2
extension: 0.2.0

**Comment by callmekatootie** [comment]
Valid issue. Able to reproduce.

**Comment by callmekatootie** [comment]
Update: The fix is in. Will be part of the next release

**Comment by callmekatootie** [comment]
Fixed in [0.3.0](https://github.com/topcoder-platform/ide-ext-vscode/releases/tag/v0.3.0)
