### ISSUE TITLE
Unable to access Topcoder 

### ISSUE THREAD

**Issue by samuraiV** [topcoder-platform/ide-ext-vscode#66]
Issue Type: <b>Bug</b>

1. configure your credentials under: 
     TCVSCode IDE › Credentials: Password
     TCVSCode IDE › Credentials: Username
2. run command 
     Topcoder: Login

Expected result is to connect to Topcoder. 

Instead I am getting: 
Error: Failed to authenticate user. Please check your settings and try again.

Extension version: 0.2.0
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 4.15.0-74-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2745)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|7.46GB (0.15GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by callmekatootie** [comment]
@samuraiV Are you trying to login to dev instance or prod instance

**Comment by samuraiV** [comment]
not sure, how do we check it?
I just installed the extension from VsCode Extensions viewlet.

**Comment by callmekatootie** [comment]
At the bottom right, you can see the environment - it will say prod or dev:

![image](https://user-images.githubusercontent.com/2317133/73330148-f105e380-4285-11ea-9eec-df41c82b5f14.png)

What does yours read?

**Comment by samuraiV** [comment]
Actually I am not getting either.
Here is how my screen looks like - 
![vscode](https://user-images.githubusercontent.com/4892475/73330463-dbdd8480-4286-11ea-8199-a02bcdfe2aa4.png)

**Comment by callmekatootie** [comment]
You appear to have hidden the status bar. Could you go to View in the menu, then click on Appearance and then click on Show Status Bar to view the status bar.

And then you can check if you are in dev or prod environment

**Comment by callmekatootie** [comment]
[This](https://code.visualstudio.com/assets/docs/getstarted/userinterface/hero.png) is how it should look like

**Comment by samuraiV** [comment]
Ohh I got it. 
It says - TC Env: Prod

**Comment by callmekatootie** [comment]
I see the VSCode version now - this issue will be resolved in 0.3.0+ versions.

It's not yet published to marketplace but you can get the latest version [here](https://github.com/topcoder-platform/ide-ext-vscode/releases) (See assets)

**Comment by callmekatootie** [comment]
I will let you know once the latest extension is available in the marketplace

**Comment by samuraiV** [comment]
I installed the extension manually using the vsix from v0.3.1. 
And its working
Thanks for your help

**Comment by callmekatootie** [comment]
You can now pull the latest version from the [marketplace](https://marketplace.visualstudio.com/items?itemName=Topcoder.topcoder-workflow)
